server:
  port: 9092
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
            

    